name: Publish multi-arch Docker images

on:
    push:
        branches:
            - master

jobs:
    release:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
                
        steps:
        -
            name: Checkout
            uses: actions/checkout@v2
        -
            name: Set Release Tag
            run: |
                image_name="${{secrets.DOCKER_USERNAME}}/apt-cacher-ng"
                date=$(date '+%Y-%m-%d')
                apt-cacher-ng-version="apt-cacher-ng-3.6.4"
                full="${apt-cacher-ng-version}-${date}"
                tags="${image_name}:${apt-cacher-ng-version},${image_name}:${full},${image_name}:latest"
                echo "RELEASE_TAGS=${tags}" >> $GITHUB_ENV
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v1
            with:
                platforms: all
        -
            name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1
        -
            name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
        -
            name: Build and push
            uses: docker/build-push-action@v2
            with:
                context: .
                platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
                push: true
                tags: ${{ env.RELEASE_TAGS }}
